name: space_trash
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_feather_icons: ^2.0.0+1
  flutter:
    sdk: flutter
  flutter_modular: ^4.1.0+1
  flutter_triple: ^1.2.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
